### ISSUE TITLE
Boost activation performance

### ISSUE THREAD

**Issue by vinkla** [php-integrator/atom-refactoring#46]
It seem the `php-integrator-refactoring` and `php-integrator-base` takes long to active on startup. Is there a way we can make the packages load faster? It would be great when booting Atom.

<img width="833" alt="screen shot 2017-04-25 at 9 04 23 pm" src="https://cloud.githubusercontent.com/assets/499192/25403021/1acbe6ca-29fb-11e7-8ce4-941375f82ace.png">

Example from Atom's Timecop plugin. You can test this by going Packages > Timecop > Show.

**Comment by Gert-dev** [comment]
I think this happens because, on activation, the refactoring package classes are creating some services early, including some views. It is probably the cumulation of these relatively "small" hits that results in the relatively large activation time.

Something I could investigate is simply using a getter method that instantiates the object if it hasn't been instantiated yet as soon as it is first required. This would move the load to the moment it is first requested.

I'm planning to (try and) move most functionality currently provided by the php-integrator-* packages into the core as much as possible for 3.0.0 to allow more advanced functionality in the future and improve performance (also to allow reusability in other editors, eventually), which is why activity on other repositories than the base has somewhat ceased.

Doing this involves implementing the bulk functionality in the core itself and providing a thinner client-side (JavaScript/CoffeeScript/Atom) interface in the base package. Whilst doing this, I'm trying to fix some of the most important outstanding issues. This ticket seems like a good candidate to include in that effort.

**Comment by vinkla** [comment]
Sounds good! Would be cool if we could move everything into one package and just toggle the features.

**Comment by vinkla** [comment]
With the future release of 3.0.0 of the base package, can we close this issue?

**Comment by Gert-dev** [comment]
I've already moved a couple of packages to the core, but due to the time it's been since the last notable release, the scope of moving everything, and the amount of new features and bugfixes that have happened in the meantime, I'm thinking of doing the remaining packages (autocompletion, refactoring, navigation and annotations) in a 3.x release or later (I've already moved tooltips, linting and call tips).

This also means that this CoffeeScript package will have to live on for a little longer than I initially planned until I can move it to the core.

Thanks for reminding me of this ticket, I'm trying to not add too many new features in the packages that I will have to rewrite later in PHP anyway, but I'm going to try to get this in before the 3.0.0 release as I do value good performance and activiation time really shouldn't be as large as it currently is.

**Comment by vinkla** [comment]
I'm glad you're making progress and centralize the packages. This will make it a lot easier for newcomers to understand. 

> …in a 3.x release or later…

Is it possible to test the new version now? I would happily help to debug and report bugs (if any). When is the ETA on the new version?

**Comment by Gert-dev** [comment]
@vinkla I've responded to your question regarding to 3.0 in https://github.com/php-integrator/atom-base/issues/297 :-).
