### ISSUE TITLE
ask how to generate docblock

### ISSUE THREAD

**Issue by fericosali** [php-integrator/atom-refactoring#55]
hi, your job to make php-integrator was good.. however i want ask you how to generate docblock properly? let say i had this function

public function testBlock($data, $username)
{
     xxxxx
     return xx;
}

i try to block all the function but it make the block to generate function in function..
thanks anyway :))

**Comment by Gert-dev** [comment]
Thanks!

Do you mean that the docblock is showing up inside the function itself rather than above the function?

```php
public function testBlock($data, $username)
/**
 * ...
 */
{
    ...
```

Instead of above it?


```php
/**
 * ...
 */
public function testBlock($data, $username)
{
    ...
```

In some circumstances this can happen as the position for the docblock is derived from the start line of the method, which is updated when the next indexing occurs. This in turn can take a while on slower hardware or simply fail if the file contains errors, hence the incorrect localisation of the docblock.

**Comment by Gert-dev** [comment]
Closing this as this package will be merged into the [base](https://github.com/php-integrator/atom-base/) package.
